USE ROLE ACCOUNTADMIN;

-- creating the `transform` role
CREATE ROLE IF NOT EXISTS transform;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Creating the default warehouse 
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Creating the `dbt` user and assign to role
CREATE USER IF NOT EXISTS dbt
  PASSWORD='******'
  LOGIN_NAME='****'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE='transform'
  DEFAULT_NAMESPACE='REAL_ESTATE_DB.RAW'
  COMMENT='DBT user used for data transformation';
GRANT ROLE transform to USER dbt;

-- Creating our database and schemas
CREATE DATABASE IF NOT EXISTS AIRBNB;
CREATE SCHEMA IF NOT EXISTS AIRBNB.RAW;

-- Set up permissions to role `transform`
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE transform; 
GRANT ALL ON DATABASE REAL_ESTATE_DB to ROLE transform;
GRANT ALL ON ALL SCHEMAS IN DATABASE REAL_ESTATE_DB to ROLE transform;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE REAL_ESTATE_DB to ROLE transform;
GRANT ALL ON ALL TABLES IN SCHEMA REAL_ESTATE_DB.RAW to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA REAL_ESTATE_DB.RAW to ROLE transform;




